networks:
  docker-local_net:
    driver: bridge

services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI

  postgres-db:
    container_name: 'postgres-db'
    image: postgres:15.1
    networks:
      - docker-local_net
    environment:
      - POSTGRES_USER=qlarr
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=qlarrdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data

  postgres_admin:
    container_name: postgres_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: qlarr@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./docker-data/postgres-admin-data:/var/lib/postgresql/data
      - ./docker-data/postgres-admin-bkp:/var/lib/postgresql/bkp
    ports:
      - "5050:80"
    networks:
      - docker-local_net
    restart: unless-stopped

  backend-app:
    container_name: 'qlarr-backend'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - docker-local_net
    depends_on:
      - postgres-db
    restart: unless-stopped
    volumes:
      - $HOME/qlarr-data/survey-files:/var/qlarr/resources
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DB_URL=jdbc:postgresql://postgres-db:5432/qlarrdb
      - DB_USER=qlarr
      - FILE_SYSTEM_ROOT_FOLDER=/var/qlarr/resources
      - DB_PASSWORD=password
      - MAIL_HOST=
      - MAIL_SMTP_SSL=
      - MAIL_SMTP_STARTTLS=
      - MAIL_PORT=
      - MAIL_PASSWORD=
      - MAIL_USERNAME=
      - FRONTEND_URL=http://localhost
      - JWT_SECRET=
  ai-generator:
    build:
      context: ../ai-generator
      args:
        - GEMINI_API_KEY=
        - PORT=4000
    ports:
      - "4000:4000"
    restart: always

  react-app:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        VITE_FRONT_END_HOST: "localhost"
        VITE_PROTOCOL: "http"
        VITE_BE_URL: "http://localhost:8080"
        VITE_CLOUD_URL: "https://stg.api.qlarr.com"
    depends_on:
      - backend-app
    ports:
      - "80:80"