version: '3.1'

networks:
  docker-local_net:
    driver: bridge

services:

  local-postgres:
    container_name: 'local-postgres'
    image: postgres:15.1
    networks:
      - docker-local_net
    environment:
      - POSTGRES_USER=qlarr
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=qlarrdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - $HOME/data/local-postgres-data:/var/lib/postgresql/data

#  postgres_admin:
#    container_name: postgres_admin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: qlarr@pgadmin.org
#      PGADMIN_DEFAULT_PASSWORD: password
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - $HOME/data/postgres-admin-data:/var/lib/postgresql/data
#      - $HOME/data/postgres-admin-bkp:/var/lib/postgresql/bkp
#    ports:
#      - "5050:80"
#    networks:
#      - docker-local_net
#    restart: unless-stopped

  app:
    container_name: 'qlarr-backend'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - docker-local_net
    depends_on:
      - local-postgres
    restart: unless-stopped
