spring:
  profiles:
    default: local
  datasource:
    url: jdbc:postgresql://localhost:5432/frankiedb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        ddl-auto: none
    open-in-view: false
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    date-time-format: yyyy-MM-dd HH:mm:ss
auth:
  googleClientId: 464768435207-uhlij21kj0kn0tetqqj4292iedfeiogf.apps.googleusercontent.com
jwt:
  activeExpirationMs: 3600000
  resetExpirationMs: 3600000
  refreshExpirationMs: 31536000000
  secret: ${JWT_SECRET}
mail:
  host: smtp.gmail.com
  port: 465
  password: ${MAIL_PASSWORD}
  email: ${MAIL_EMAIL}
  mock: false
env:
  test: false
  s3:
    bucketName: frankie-testing
frontend:
  host: frankie.app:3000
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/frankiedb
    username: frankie
    password: password
mail:
  password: owzrmumizhrggtul
  email: askoura@gmail.com
aws:
  accessId: AKIASE767Z45RDFNMOZD
  secretKey: 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
  s3:
    bucketName: frankie-testing
jwt:
  secret: lGYGGQSGHvq1lIw6Y3Ipy06H8SpSgHcARdPztZAS7Ug=
frontend:
  host: frankie.app:3000
---
spring:
  config:
    activate:
      on-profile: staging
  datasource:
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver
    url: jdbc-secretsmanager:postgresql://qlarr-stg.cy0f33fng7df.eu-central-1.rds.amazonaws.com:5432/qlarrdb
    username: staging/qlarr-backend/rds
mail:
  password: ${EMAIL_PASSWORD}
  email: ${EMAIL_MAIL}
aws:
  s3:
    bucketName: 148174262075-qlarr-backend-stg
jwt:
  secret: ${JWT_SECRET}
frontend:
  host: stg.console.qlarr.com
auth:
  googleClientId: ${GOOGLE_CLIENT_ID}
---
