spring:
  profiles:
    default: local
  datasource:
    url: jdbc:postgresql://localhost:5432/frankiedb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        ddl-auto: none
    open-in-view: false
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    date-time-format: yyyy-MM-dd HH:mm:ss
auth:
  googleClientId: 464768435207-uhlij21kj0kn0tetqqj4292iedfeiogf.apps.googleusercontent.com
jwt:
  activeExpirationMs: 3600000
  resetExpirationMs: 3600000
  resetExpirationForNewUsersMs: 2592000000
  refreshExpirationMs: 31536000000
  secret: lGYGGQSGHvq1lIw6Y3Ipy06H8SpSgHcARdPztZAS7Ug=
mail:
  host: smtp.gmail.com
  port: 465
  password: ${MAIL_PASSWORD}
  email: ${MAIL_EMAIL}
  mock: false
env:
  test: false
  s3:
    bucketName: frankie-testing
frontend:
  host: frankie.app:3000
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/frankiedb
    username: frankie
    password: password
mail:
  password: owzrmumizhrggtul
  email: askoura@gmail.com
fileSystem:
  rootFolder: src/main/resources/root
jwt:
  secret: lGYGGQSGHvq1lIw6Y3Ipy06H8SpSgHcARdPztZAS7Ug=
frontend:
  host: frankie.app:3000
#  This belongs to askoura@gmail.com
guestSurveysTenant: fb667f6f-f61c-4180-9603-da5ffa8a2457
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://local-postgres:5432/frankiedb
    username: frankie
    password: password
mail:
  password: owzrmumizhrggtul
  email: askoura@gmail.com
jwt:
  secret: lGYGGQSGHvq1lIw6Y3Ipy06H8SpSgHcARdPztZAS7Ug=
frontend:
  host: frankie.app:3000
#  This belongs to askoura@gmail.com
guestSurveysTenant: fb667f6f-f61c-4180-9603-da5ffa8a2457

