spring:
  profiles:
    default: local
  datasource:
    url: jdbc:postgresql://localhost:5432/qlarrdb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        ddl-auto: none
    open-in-view: false
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    date-time-format: yyyy-MM-dd HH:mm:ss
jwt:
  activeExpirationMs: 3600000
  resetExpirationMs: 3600000
  resetExpirationForNewUsersMs: 2592000000
  refreshExpirationMs: 31536000000
mail:
  host: smtp.gmail.com
  port: 465
  password: ${MAIL_PASSWORD}
  email: ${MAIL_EMAIL}
  mock: false
env:
  test: false
frontend:
  host: localhost:3000
enterprise.domain: https://stg.api.qlarr.com/
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/qlarrdb
    username: qlarr
    password: password
mail:
  password: owzrmumizhrggtul
  email: askoura@gmail.com
fileSystem:
  rootFolder: src/main/resources/root
jwt:
  secret: lGYGGQSGHvq1lIw6Y3Ipy06H8SpSgHcARdPztZAS7Ug=
frontend:
  host: localhost:3000
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres-db:5432/qlarrdb
    username: qlarr
    password: password
mail:
  password: owzrmumizhrggtul
  email: askoura@gmail.com
fileSystem:
  rootFolder: /var/qlarr/resources
jwt:
  secret: lGYGGQSGHvq1lIw6Y3Ipy06H8SpSgHcARdPztZAS7Ug=
frontend:
  host: localhost:3000