spring:
  profiles:
    default: local
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        ddl-auto: none
    open-in-view: false
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    date-time-format: yyyy-MM-dd HH:mm:ss
jwt:
  activeExpirationMs: 3600000
  resetExpirationMs: 3600000
  resetExpirationForNewUsersMs: 2592000000
  refreshExpirationMs: 31536000000
  secret: {JWT_SECRET}
mail:
  host: ${MAIL_HOST}
  port: ${MAIL_PORT}
  ssl: ${MAIL_SMTP_SSL}
  starttls: ${MAIL_SMTP_STARTTLS}
  password: ${MAIL_PASSWORD}
  username: ${MAIL_USERNAME}
frontendUrl: ${FRONTEND_URL}
fileSystem:
  rootFolder: ${FILE_SYSTEM_ROOT_FOLDER}
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/qlarrdb
    username: qlarr
    password: password
mail:
  host: localhost
  port: 1025
  ssl: false
  startTls: false
  password:
  username: username
fileSystem:
  rootFolder: local-data
jwt:
  secret: lGYGGQSGHvq1lIw6Y3Ipy06H8SpSgHcARdPztZAS7Ug=
frontendUrl: http://localhost:3000