### get all active users
GET {{host}}/user
Accept: application/json

### try to get an unknown user
GET {{host}}/user/01a540f1-e861-4be8-8977-b8b19e24930b
Accept: application/json

### add a new user and copy the id of the fresh created user into a variable to use it for the next request
POST {{host}}/user/signup
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "James",
  "email": "john@email.com",
  "roles": [
    "super_admin"
  ]
}
> {%
    client.global.set("userId", response.body.id);
    client.global.set("token", response.body.auth.token);
%}

### get the fresh created user
GET {{host}}/user/{{userId}}
Accept: application/json

### get all active users filtered by email
GET {{host}}/user?email=john@email.com
Accept: application/json

### get all active users filtered by first name
GET {{host}}/user?firstName=John
Accept: application/json

### get all active users filtered by last name
GET {{host}}/user?lastName=james
Accept: application/json

### get all active users filtered by all values
GET {{host}}/user?email=john@email.com&firstName=John&lastName=James
Accept: application/json

### get all active users filtered by all values ignore case
GET {{host}}/user?email=John@Email.Com&firstName=john&lastName=james
Accept: application/json

### get all active users filtered by all values ignore case
GET {{host}}/user/count_by_role
Accept: application/json

### get all events for user
GET {{host}}/user/3d4f22d3-c49d-490a-ac34-605d200b8f4a/event
Accept: application/json
Authorization: "Bearer eyJhbGciOiJIUzUxMiJ9..1mjIMvDmoSfY7p2UN5YxG_x_0XPL8tPSYnRJ655E4sZUiqPH6j5F4q6ACk7y8NRLPIF301GC_5zQBy1B7B-1dQ"
